version: '3'
services:

  postgres:
    image: postgres:9.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: cimba
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: cimba@fe.up.pt
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres

  frontend:
    build: ./application
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./application/:/app
    env_file:
      - application/.env
    stdin_open: true

  backend:
    build: ./backend
    container_name: backend
    ports: 
      - "8080:8080"
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./backend/.env
    depends_on: 
      - postgres

