version: '3'
services:

  postgres:
    image: postgres:9.4
    restart: always
    environment:
      POSTGRES_USER: cimba
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: cimba@fe.up.pt
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres
